use_frameworks!

platform :ios, '8.0'

target 'ComponentMiddleware_Example' do
  pod 'ComponentMiddleware', :path => '../'

  target 'ComponentMiddleware_Tests' do
    inherit! :search_paths

    
  end
end
